name: Check formatting

on: 
  push:
  pull_request:
    branches:
      - '**'

jobs:
  spotless:
    name: Run Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck
